# Generated by Django 4.1.2 on 2022-10-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jop_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default=None, max_length=20)),
                ('description', models.TextField(default=None, max_length=1500)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=1)),
            ]
        )
    ]
