# Generated by Django 4.1.2 on 2022-10-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gander',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer to not respons', 'Prefer to not respons')], null=True, default=None, max_length=30),
        ),
    ]
